name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H 3.111.157.102 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/deploy_key ubuntu@3.111.157.102 '
            cd /var/www/app1 &&
            git pull origin main &&
            cd /var/www/app2 &&
            git pull origin main &&
            sudo systemctl restart php8.2-fpm &&
            sudo systemctl reload nginx
          '
