name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 3.111.157.102
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /var/www/app1
          git pull origin main
          cd /var/www/app2
          git pull origin main
          sudo systemctl restart php8.2-fpm
          sudo systemctl reload nginx
