name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: 3.111.157.102
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /var/www/app1
          sudo git pull origin main
          sudo chown -R www-data:www-data .
          sudo chmod -R 775 .
          
          cd /var/www/app2
          sudo git pull origin main
          sudo chown -R www-data:www-data .
          sudo chmod -R 775 .
          
          sudo systemctl restart php8.2-fpm
          sudo systemctl reload nginx
