name: Deploy Code Changes

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Execute Remote SSH Commands
      uses: fifsky/ssh-action@master
      with:
        host: 3.111.157.102
        user: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        command: cd /var/www && sudo bash deploy.sh
